services:
  haejoong.com-db:
    image: postgres:15-alpine
    container_name: haejoong.com-db
    expose:
      - 5432
    volumes:
      - haejoong.com-db-volume:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - haejoong.com

  haejoong.com-cache:
    image: redis:7.2-alpine
    container_name: haejoong.com-cache
    expose:
      - 6379
    volumes:
      - haejoong.com-cache-volume:/data
    restart: always
    networks:
      - haejoong.com

volumes:
  haejoong.com-db-volume:
    name: haejoong.com-db-volume
  haejoong.com-cache-volume:
    name: haejoong.com-cache-volume

networks:
  haejoong.com:
